#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     liftL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     liftR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     acquirer,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     blank,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    goalClamp,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    autonExtend,          tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    autonFlip,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Copyright Stuy Fission 310
/**
 * Authored by Alvin Lin (alvin.lin@stuypulse.com)
 * http://omgimanerd.github.io
 * http://310fission.com
 * This file is a basic autonomous program used for testing.
 */

void preventTwitch() {
	servo[autonExtend] = 230;
	servo[autonFlip] = 180;
}

task main() {
	nxtDisplayString(2, "autonExtend: %i", ServoValue[autonExtend]);
	nxtDisplayString(3, "autonFlip: %i", ServoValue[autonFlip]);
	servo[autonExtend] = 0;
	servo[autonFlip] = 0;
	servoChangeRate[autonFlip] = 2;
	wait1Msec(2000);
	servo[autonFlip] = 180;
	wait1Msec(4000);
	servo[autonExtend] = 230;
	wait1Msec(4000);
}
