#pragma config(Sensor, S2,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RobotC/drivers/HTSPB-driver.h"

task main() {
  
  // Set B0 as an output port
  // All output ports must be set up before outputting.
  // 0x01 (hex) is 00000001 in binary
  // Output is 5V.
  HTSPBwriteIO(HTSPB, 0x01);
  wait1Msec(1000);
  HTSPBwriteIO(HTSPB, 0x00);
  wait1Msec(1000);
  while(true) {
    if (HTSPBreadIO(HTSPB, 0x02) != 0) {
      HTSPBwriteIO(HTSPB, 0x01);
    } else {
      HTSPBwriteIO(HTSPB, 0x00);
    }
  }
}
