#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "RobotC/drivers/HTSPB-driver.h"

task main() {

  // Set B0 for output
	// Output is 5V.
  HTSPBsetupIO(HTSPB, 0x1);

  while(true) {
    HTSPBwriteIO(HTSPB, 0x00);
    wait1Msec(1500);
    HTSPBwriteIO(HTSPB, 0x01);
    wait1Msec(1500);
  }
}
